Public Class ColorDistribution

    Private Sub ColorDistribution_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        PictureBox1.BackColor = Color.FromName(Main_Form.strColList(1))
        PictureBox2.BackColor = Color.FromName(Main_Form.strColList(2))
        PictureBox3.BackColor = Color.FromName(Main_Form.strColList(3))
        PictureBox4.BackColor = Color.FromName(Main_Form.strColList(4))
        PictureBox5.BackColor = Color.FromName(Main_Form.strColList(5))
        PictureBox6.BackColor = Color.FromName(Main_Form.strColList(6))
        PictureBox7.BackColor = Color.FromName(Main_Form.strColList(7))
        PictureBox8.BackColor = Color.FromName(Main_Form.strColList(8))
        PictureBox9.BackColor = Color.FromName(Main_Form.strColList(9))
        PictureBox10.BackColor = Color.FromName(Main_Form.strColList(10))
        PictureBox11.BackColor = Color.FromName(Main_Form.strColList(11))
        PictureBox12.BackColor = Color.FromName(Main_Form.strColList(12))
        PictureBox13.BackColor = Color.FromName(Main_Form.strColList(13))
        PictureBox14.BackColor = Color.FromName(Main_Form.strColList(14))
        PictureBox15.BackColor = Color.FromName(Main_Form.strColList(15))
        PictureBox16.BackColor = Color.FromName(Main_Form.strColList(16))
        PictureBox17.BackColor = Color.FromName(Main_Form.strColList(17))
        PictureBox18.BackColor = Color.FromName(Main_Form.strColList(18))
        PictureBox19.BackColor = Color.FromName(Main_Form.strColList(19))
        PictureBox20.BackColor = Color.FromName(Main_Form.strColList(20))
        PictureBox21.BackColor = Color.FromName(Main_Form.strColList(21))
        PictureBox22.BackColor = Color.FromName(Main_Form.strColList(22))
        PictureBox23.BackColor = Color.FromName(Main_Form.strColList(23))
        PictureBox24.BackColor = Color.FromName(Main_Form.strColList(24))
        PictureBox25.BackColor = Color.FromName(Main_Form.strColList(25))
        PictureBox26.BackColor = Color.FromName(Main_Form.strColList(26))
        PictureBox27.BackColor = Color.FromName(Main_Form.strColList(27))
        PictureBox28.BackColor = Color.FromName(Main_Form.strColList(28))
        PictureBox29.BackColor = Color.FromName(Main_Form.strColList(29))
    End Sub
End Class